export default [
	{
		key: 1,
		name: 'Mərkəzi Orta Məktəb',
		city: 'Bakı',
		region: 'Abşeron',
		student_count: 1200,
		type: 'Dövlət',
	},
	{
		key: 2,
		name: 'Lənkəran Orta Məktəbi',
		city: 'Lənkəran',
		region: 'Lənkəran',
		student_count: 1150,
		type: 'Dövlət',
	},
	{
		key: 3,
		name: 'Şərq Orta Məktəbi',
		city: 'Gəncə',
		region: 'Gəncə',
		student_count: 1000,
		type: 'Özəl',
	},
	{
		key: 4,
		name: 'Günəşli Orta Məktəb',
		city: 'Sumqayıt',
		region: 'Sumqayıt',
		student_count: 1300,
		type: 'Dövlət',
	},
	{
		key: 5,
		name: 'Qərb Orta Məktəbi',
		city: 'Şəki',
		region: 'Şəki',
		student_count: 950,
		type: 'Xüsusi',
	},
	{
		key: 6,
		name: 'Sərvət Orta Məktəbi',
		city: 'Şəmkir',
		region: 'Şəmkir',
		student_count: 900,
		type: 'Özəl',
	},
	{
		key: 7,
		name: 'Çayqırağı Orta Məktəb',
		city: 'Mingəçevir',
		region: 'Mingəçevir',
		student_count: 1200,
		type: 'Dövlət',
	},
	{
		key: 8,
		name: 'Palıd Orta Məktəbi',
		city: 'Şirvan',
		region: 'Şirvan',
		student_count: 1150,
		type: 'Xüsusi',
	},
	{
		key: 9,
		name: 'Şamlıq Orta Məktəbi',
		city: 'Bərdə',
		region: 'Bərdə',
		student_count: 950,
		type: 'Özəl',
	},
	{
		key: 10,
		name: 'Əsas Orta Məktəb',
		city: 'Naxçıvan',
		region: 'Naxçıvan',
		student_count: 1500,
		type: 'Dövlət',
	},
	{
		key: 11,
		name: 'Yüksək Orta Məktəb',
		city: 'Qəbələ',
		region: 'Qəbələ',
		student_count: 1000,
		type: 'Xüsusi',
	},
	{
		key: 12,
		name: 'Vadiməktəb Orta Məktəbi',
		city: 'Quba',
		region: 'Quba',
		student_count: 1200,
		type: 'Dövlət',
	},
	{
		key: 13,
		name: 'Dağ Orta Məktəbi',
		city: 'Qusar',
		region: 'Qusar',
		student_count: 1300,
		type: 'Dövlət',
	},
	{
		key: 14,
		name: 'Liman Orta Məktəbi',
		city: 'Liman',
		region: 'Liman',
		student_count: 1150,
		type: 'Özəl',
	},
	{
		key: 15,
		name: 'Günbatımı Orta Məktəbi',
		city: 'Biləsuvar',
		region: 'Biləsuvar',
		student_count: 1250,
		type: 'Dövlət',
	},
	{
		key: 16,
		name: 'Qırmızı Palıd Orta Məktəbi',
		city: 'Tovuz',
		region: 'Tovuz',
		student_count: 1200,
		type: 'Xüsusi',
	},
	{
		key: 17,
		name: 'Gölkənarı Orta Məktəbi',
		city: 'Astara',
		region: 'Astara',
		student_count: 1300,
		type: 'Dövlət',
	},
	{
		key: 18,
		name: 'Meşə Park Orta Məktəbi',
		city: 'Şamaxı',
		region: 'Şamaxı',
		student_count: 1150,
		type: 'Özəl',
	},
	{
		key: 19,
		name: 'Çəmən Orta Məktəbi',
		city: 'Sabirabad',
		region: 'Sabirabad',
		student_count: 1000,
		type: 'Xüsusi',
	},
	{
		key: 20,
		name: 'Şimal Orta Məktəbi',
		city: 'Zaqatala',
		region: 'Zaqatala',
		student_count: 1200,
		type: 'Dövlət',
	},
]
