export default [
	{
		key: 1,
		name: 'Yaşılçay Əsas Məktəbi',
		city: 'Bakı',
		region: 'Abşeron',
		student_count: 500,
		type: 'Dövlət',
	},
	{
		key: 2,
		name: 'Lənkəran Əsas Məktəbi',
		city: 'Lənkəran',
		region: 'Lənkəran',
		student_count: 450,
		type: 'Dövlət',
	},
	{
		key: 3,
		name: 'Xanlar Məktəbi',
		city: 'Gəncə',
		region: 'Gəncə',
		student_count: 400,
		type: 'Özəl',
	},
	{
		key: 4,
		name: 'Günəşli Məktəbi',
		city: 'Sumqayıt',
		region: 'Sumqayıt',
		student_count: 600,
		type: 'Dövlət',
	},
	{
		key: 5,
		name: 'Qərb Məktəbi',
		city: 'Şəki',
		region: 'Şəki',
		student_count: 350,
		type: 'Xüsusi',
	},
	{
		key: 6,
		name: 'Sərvət Məktəbi',
		city: 'Şəmkir',
		region: 'Şəmkir',
		student_count: 300,
		type: 'Özəl',
	},
	{
		key: 7,
		name: 'Çayqırağı Məktəbi',
		city: 'Mingəçevir',
		region: 'Mingəçevir',
		student_count: 500,
		type: 'Dövlət',
	},
	{
		key: 8,
		name: 'Palıd Məktəbi',
		city: 'Şirvan',
		region: 'Şirvan',
		student_count: 450,
		type: 'Xüsusi',
	},
	{
		key: 9,
		name: 'Şamlıq Məktəbi',
		city: 'Bərdə',
		region: 'Bərdə',
		student_count: 350,
		type: 'Özəl',
	},
	{
		key: 10,
		name: 'Əsas Məktəb',
		city: 'Naxçıvan',
		region: 'Naxçıvan',
		student_count: 700,
		type: 'Dövlət',
	},
	{
		key: 11,
		name: 'Yüksək Məktəb',
		city: 'Qəbələ',
		region: 'Qəbələ',
		student_count: 400,
		type: 'Xüsusi',
	},
	{
		key: 12,
		name: 'Vadiməktəb',
		city: 'Quba',
		region: 'Quba',
		student_count: 500,
		type: 'Dövlət',
	},
	{
		key: 13,
		name: 'Dağ Məktəbi',
		city: 'Qusar',
		region: 'Qusar',
		student_count: 600,
		type: 'Dövlət',
	},
	{
		key: 14,
		name: 'Liman Məktəbi',
		city: 'Liman',
		region: 'Liman',
		student_count: 450,
		type: 'Özəl',
	},
	{
		key: 15,
		name: 'Günbatımı Məktəbi',
		city: 'Biləsuvar',
		region: 'Biləsuvar',
		student_count: 550,
		type: 'Dövlət',
	},
	{
		key: 16,
		name: 'Qırmızı Palıd Məktəbi',
		city: 'Tovuz',
		region: 'Tovuz',
		student_count: 500,
		type: 'Xüsusi',
	},
	{
		key: 17,
		name: 'Gölkənarı Məktəbi',
		city: 'Astara',
		region: 'Astara',
		student_count: 600,
		type: 'Dövlət',
	},
	{
		key: 18,
		name: 'Meşə Park Məktəbi',
		city: 'Şamaxı',
		region: 'Şamaxı',
		student_count: 450,
		type: 'Özəl',
	},
	{
		key: 19,
		name: 'Çəmən Məktəbi',
		city: 'Sabirabad',
		region: 'Sabirabad',
		student_count: 400,
		type: 'Xüsusi',
	},
	{
		key: 20,
		name: 'Şimal Məktəbi',
		city: 'Zaqatala',
		region: 'Zaqatala',
		student_count: 500,
		type: 'Dövlət',
	},
]
