/*

    it's just a sample data :)

*/
export default [
	{
		key: 1,
		established_year: 1919,
		name: 'Bakı Universiteti',
		city: 'Bakı',
		region: 'Abşeron',
		student_count: 20000,
		type: 'Dövlət',
		academic_level: 'Bakalavr',
	},
	{
		key: 2,
		established_year: 1930,
		name: 'Lənkəran Universiteti',
		city: 'Lənkəran',
		region: 'Lənkəran',
		student_count: 22000,
		type: 'Dövlət',
		academic_level: 'Magistr',
	},
	{
		key: 3,
		established_year: 1920,
		name: 'Gəncə Universiteti',
		city: 'Gəncə',
		region: 'Gəncə',
		student_count: 18000,
		type: 'Özəl',
		academic_level: 'Doktorantura',
	},
	{
		key: 4,
		established_year: 1960,
		name: 'Sumqayıt Texniki Universiteti',
		city: 'Sumqayıt',
		region: 'Sumqayıt',
		student_count: 25000,
		type: 'Dövlət',
		academic_level: 'Bakalavr',
	},
	{
		key: 5,
		established_year: 1945,
		name: 'Şəki Dövlət Universiteti',
		city: 'Şəki',
		region: 'Şəki',
		student_count: 16000,
		type: 'Dövlət',
		academic_level: 'Magistr',
	},
	{
		key: 6,
		established_year: 1985,
		name: 'Şəmkir Universiteti',
		city: 'Şəmkir',
		region: 'Şəmkir',
		student_count: 15000,
		type: 'Özəl',
		academic_level: 'Doktorantura',
	},
	{
		key: 7,
		established_year: 1975,
		name: 'Mingəçevir Universiteti',
		city: 'Mingəçevir',
		region: 'Mingəçevir',
		student_count: 20000,
		type: 'Dövlət',
		academic_level: 'Bakalavr',
	},
	{
		key: 8,
		established_year: 1950,
		name: 'Şirvan Universiteti',
		city: 'Şirvan',
		region: 'Şirvan',
		student_count: 22000,
		type: 'Dövlət',
		academic_level: 'Magistr',
	},
	{
		key: 9,
		established_year: 1990,
		name: 'Bərdə Universiteti',
		city: 'Bərdə',
		region: 'Bərdə',
		student_count: 15000,
		type: 'Özəl',
		academic_level: 'Doktorantura',
	},
	{
		key: 10,
		established_year: 1935,
		name: 'Naxçıvan Universiteti',
		city: 'Naxçıvan',
		region: 'Naxçıvan',
		student_count: 30000,
		type: 'Dövlət',
		academic_level: 'Bakalavr',
	},
	{
		key: 11,
		established_year: 1970,
		name: 'Qəbələ Universiteti',
		city: 'Qəbələ',
		region: 'Qəbələ',
		student_count: 18000,
		type: 'Dövlət',
		academic_level: 'Magistr',
	},
	{
		key: 12,
		established_year: 1980,
		name: 'Quba Universiteti',
		city: 'Quba',
		region: 'Quba',
		student_count: 20000,
		type: 'Dövlət',
		academic_level: 'Doktorantura',
	},
	{
		key: 13,
		established_year: 1995,
		name: 'Qusar Universiteti',
		city: 'Qusar',
		region: 'Qusar',
		student_count: 25000,
		type: 'Dövlət',
		academic_level: 'Bakalavr',
	},
	{
		key: 14,
		established_year: 2000,
		name: 'Liman Universiteti',
		city: 'Liman',
		region: 'Liman',
		student_count: 22000,
		type: 'Özəl',
		academic_level: 'Magistr',
	},
	{
		key: 15,
		established_year: 1965,
		name: 'Biləsuvar Universiteti',
		city: 'Biləsuvar',
		region: 'Biləsuvar',
		student_count: 26000,
		type: 'Dövlət',
		academic_level: 'Doktorantura',
	},
	{
		key: 16,
		established_year: 1988,
		name: 'Tovuz Universiteti',
		city: 'Tovuz',
		region: 'Tovuz',
		student_count: 20000,
		type: 'Dövlət',
		academic_level: 'Bakalavr',
	},
	{
		key: 17,
		established_year: 1992,
		name: 'Astara Universiteti',
		city: 'Astara',
		region: 'Astara',
		student_count: 25000,
		type: 'Dövlət',
		academic_level: 'Magistr',
	},
	{
		key: 18,
		established_year: 1978,
		name: 'Şamaxı Universiteti',
		city: 'Şamaxı',
		region: 'Şamaxı',
		student_count: 22000,
		type: 'Özəl',
		academic_level: 'Doktorantura',
	},
	{
		key: 19,
		established_year: 1982,
		name: 'Sabirabad Universiteti',
		city: 'Sabirabad',
		region: 'Sabirabad',
		student_count: 18000,
		type: 'Dövlət',
		academic_level: 'Bakalavr',
	},
	{
		key: 20,
		established_year: 1955,
		name: 'Zaqatala Universiteti',
		city: 'Zaqatala',
		region: 'Zaqatala',
		student_count: 20000,
		type: 'Dövlət',
		academic_level: 'Magistr',
	},
	{
		key: 21,
		established_year: 1990,
		name: 'Abşeron Universiteti',
		city: 'Abşeron',
		region: 'Abşeron',
		student_count: 17000,
		type: 'Özəl',
		academic_level: 'Doktorantura',
	},
	{
		key: 22,
		established_year: 1968,
		name: 'Bölgə Universiteti',
		city: 'Sumqayıt',
		region: 'Sumqayıt',
		student_count: 21000,
		type: 'Dövlət',
		academic_level: 'Bakalavr',
	},
	{
		key: 23,
		established_year: 1930,
		name: 'Mərkəzi Dövlət Universiteti',
		city: 'Şəki',
		region: 'Şəki',
		student_count: 19000,
		type: 'Dövlət',
		academic_level: 'Magistr',
	},
    {
        key: 24,
        established_year: 1985,
        name: 'Azadlıq Universiteti',
        city: 'Gəncə',
        region: 'Gəncə',
        student_count: 14000,
        type: 'Özəl',
        academic_level: 'Doktorantura',
    },
    {
        key: 25,
        established_year: 2020,
        name: 'Yalançı Onlayn Cavan Universiteti',
        city: 'Bakı',
        region: 'Abşeron',
        student_count: 22000,
        type: 'Özəl',
        academic_level: 'Bakalavr',
    },
]
